name: binary_updater
description: A library to auto-update a compiled binary from github releases.
version: 1.0.0
homepage: https://github.com/zkayia/binary_updater
issue_tracker: https://github.com/zkayia/binary_updater/issues
repository: https://github.com/zkayia/binary_updater

publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  version: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

platforms:
  linux:
  macos:
  windows:
